//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rpgGame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rpgGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ash_sheet {
            get {
                object obj = ResourceManager.GetObject("ash_sheet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ash_sheet1 {
            get {
                object obj = ResourceManager.GetObject("ash_sheet1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cecilia {
            get {
                object obj = ResourceManager.GetObject("cecilia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diego {
            get {
                object obj = ResourceManager.GetObject("diego", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap l1 {
            get {
                object obj = ResourceManager.GetObject("l1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 20
        ///800 700
        ///0	1	2	3	4	5	6	7	8	9	10	11	12	13	14	15	16	17	18	19
        ///20	21	22	23	24	25	26	27	28	29	30	31	32	33	34	35	36	37	38	39
        ///40	41	42	43	44	45	46	47	48	49	50	51	52	53	54	55	56	57	58	59
        ///60	61	62	63	64	65	66	67	68	69	70	71	72	73	74	75	76	77	78	79
        ///80	81	82	83	84	85	86	87	88	89	90	91	92	93	94	95	96	97	98	99
        ///100	101	102	103	104	105	106	107	108	109	110	111	112	113	114	115	116	117	118	119
        ///120	121	122	123	124	125	126	127	128	129	130	131	132	133	134	135	136	137	138	139
        ///140	141	142	143	144	145	146	147	148	149 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string l11 {
            get {
                return ResourceManager.GetString("l11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lc1 {
            get {
                object obj = ResourceManager.GetObject("lc1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 20
        ///800 700
        ///1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1
        ///1	1	1	1	1	1	1	1	1	1	1	1	1	1	0	0	0	0	0	1
        ///1	1	1	1	1	1	1	1	1	1	1	1	1	1	0	0	0	0	0	1
        ///1	1	1	1	1	1	1	1	1	1	1	1	1	1	0	0	0	0	0	1
        ///1	1	1	1	1	1	1	1	1	1	1	1	1	1	0	0	0	0	0	1
        ///1	1	1	1	1	1	1	1	1	1	1	1	1	1	0	0	1	0	0	1
        ///1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1
        ///1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1
        ///1	1	1	1	1	1	1	0	0	0	1	1	1	1	0	0	1	1	1	1
        ///1	1	1	1	1	1	1	0	0	0	1	1	1	1	0	0	1	1	1	1
        ///1	1	1	1	1	1	1	0	0	0	1	1	1	1	0	0	1	1	1	1
        ///1	1	1	1	1	1	1	0	0	0	1	1	1	1	1	1	1	1	1	1
        ///1	1	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lc11 {
            get {
                return ResourceManager.GetString("lc11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 20
        ///800 700
        ///0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
        ///0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
        ///0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	1	1	0
        ///0	0	1	1	1	1	0	0	0	0	0	0	0	1	1	1	0	1	1	0
        ///0	0	1	1	1	1	0	0	0	0	0	0	0	1	1	1	0	1	1	0
        ///0	0	1	1	1	1	0	0	0	0	0	1	1	1	1	1	0	1	1	0
        ///0	0	1	1	1	1	1	0	0	0	0	1	1	1	1	1	0	0	0	0
        ///0	0	0	0	0	0	1	1	1	1	1	1	1	1	1	1	1	1	1	0
        ///0	0	0	0	0	0	1	0	0	0	0	0	0	1	1	1	1	1	1	0
        ///0	0	1	1	1	1	1	0	0	0	0	0	0	1	0	0	0	0	0	0
        ///0	0	0	0	0	0	1	0	0	0	0	0	0	1	0	0	0	0	0	0
        ///0	0	0	0	0	0	1	1	1	1	1	1	1	1	1	1	1	1	1	0
        ///0	0	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lc7 {
            get {
                return ResourceManager.GetString("lc7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap libraryf {
            get {
                object obj = ResourceManager.GetObject("libraryf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000110000000000001
        ///000000000000000001
        ///000000000000000001
        ///110000000001000001
        ///110000000011000001
        ///110000000011000001
        ///110000000011000011
        ///110000000011000011
        ///110000000000000011
        ///000000000000000011
        ///111111111111111111
        ///111111111111111111
        ///111111111111111111.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap monster {
            get {
                object obj = ResourceManager.GetObject("monster", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap monster1 {
            get {
                object obj = ResourceManager.GetObject("monster1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nilton {
            get {
                object obj = ResourceManager.GetObject("nilton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paperMario {
            get {
                object obj = ResourceManager.GetObject("paperMario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paperMario1 {
            get {
                object obj = ResourceManager.GetObject("paperMario1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pared {
            get {
                object obj = ResourceManager.GetObject("pared", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pared1 {
            get {
                object obj = ResourceManager.GetObject("pared1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap piso {
            get {
                object obj = ResourceManager.GetObject("piso", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap piso1 {
            get {
                object obj = ResourceManager.GetObject("piso1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap raul {
            get {
                object obj = ResourceManager.GetObject("raul", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoo {
            get {
                object obj = ResourceManager.GetObject("zoo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoo2 {
            get {
                object obj = ResourceManager.GetObject("zoo2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoofinal {
            get {
                object obj = ResourceManager.GetObject("zoofinal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
