//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rpgGame.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rpgGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ash_sheet {
            get {
                object obj = ResourceManager.GetObject("ash_sheet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ash_sheet1 {
            get {
                object obj = ResourceManager.GetObject("ash_sheet1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cecilia {
            get {
                object obj = ResourceManager.GetObject("cecilia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diego {
            get {
                object obj = ResourceManager.GetObject("diego", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap l1 {
            get {
                object obj = ResourceManager.GetObject("l1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 20 20
        ///800 700
        ///0	1	2	3	4	5	6	7	8	9	10	11	12	13	14	15	16	17	18	19
        ///20	21	22	23	24	25	26	27	28	29	30	31	32	33	34	35	36	37	38	39
        ///40	41	42	43	44	45	46	47	48	49	50	51	52	53	54	55	56	57	58	59
        ///60	61	62	63	64	65	66	67	68	69	70	71	72	73	74	75	76	77	78	79
        ///80	81	82	83	84	85	86	87	88	89	90	91	92	93	94	95	96	97	98	99
        ///100	101	102	103	104	105	106	107	108	109	110	111	112	113	114	115	116	117	118	119
        ///120	121	122	123	124	125	126	127	128	129	130	131	132	133	134	135	136	137	138	139
        ///140	141	142	143	144	145	146	147	148	149 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string l11 {
            get {
                return ResourceManager.GetString("l11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lc1 {
            get {
                object obj = ResourceManager.GetObject("lc1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 20 20
        ///800 700
        ///1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1
        ///1	1	1	1	1	1	1	1	1	1	1	1	1	1	0	0	0	0	0	1
        ///1	1	1	1	1	1	1	1	1	1	1	1	1	1	0	0	0	0	0	1
        ///1	1	1	1	1	1	1	1	1	1	1	1	1	1	0	0	0	0	0	1
        ///1	1	1	1	1	1	1	1	1	1	1	1	1	1	0	0	0	0	0	1
        ///1	1	1	1	1	1	1	1	1	1	1	1	1	1	0	0	0	0	0	1
        ///1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1
        ///1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1
        ///1	1	1	1	1	1	1	0	0	0	1	1	1	1	0	0	1	1	1	1
        ///1	1	1	1	1	1	1	0	0	0	1	1	1	1	0	0	1	1	1	1
        ///1	1	1	1	1	1	1	0	0	0	1	1	1	1	0	0	1	1	1	1
        ///1	1	1	1	1	1	1	0	0	0	1	1	1	1	1	1	1	1	1	1
        ///1	1	 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string lc11 {
            get {
                return ResourceManager.GetString("lc11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 000110000000000001
        ///000000000000000001
        ///000000000000000001
        ///110000000001000001
        ///110000000011000001
        ///110000000011000001
        ///110000000011000011
        ///110000000011000011
        ///110000000000000011
        ///000000000000000011
        ///111111111111111111
        ///111111111111111111
        ///111111111111111111.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap monster {
            get {
                object obj = ResourceManager.GetObject("monster", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap monster1 {
            get {
                object obj = ResourceManager.GetObject("monster1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nilton {
            get {
                object obj = ResourceManager.GetObject("nilton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paperMario {
            get {
                object obj = ResourceManager.GetObject("paperMario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paperMario1 {
            get {
                object obj = ResourceManager.GetObject("paperMario1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pared {
            get {
                object obj = ResourceManager.GetObject("pared", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pared1 {
            get {
                object obj = ResourceManager.GetObject("pared1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap piso {
            get {
                object obj = ResourceManager.GetObject("piso", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap piso1 {
            get {
                object obj = ResourceManager.GetObject("piso1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap raul {
            get {
                object obj = ResourceManager.GetObject("raul", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoo {
            get {
                object obj = ResourceManager.GetObject("zoo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoo2 {
            get {
                object obj = ResourceManager.GetObject("zoo2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoofinal {
            get {
                object obj = ResourceManager.GetObject("zoofinal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
